const Libby=(()=>{const cfg=window.LIBBY_CONFIG||{};const cloud=Boolean(cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY&&!cfg.SUPABASE_URL.includes('YOUR_PROJECT_REF'));const modelApi=cfg.LIBBY_API_URL||localStorage.getItem('libby_api_url')||'/api/chat';let sb=null;const state={user:null,profile:null,memories:[],documents:[],assistantOpen:localStorage.getItem('libby_assistant_open')==='true'};const $=id=>document.getElementById(id);const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function boot(){wire();if(cloud&&window.supabase){sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});sb.auth.onAuthStateChange((_e,s)=>hydrate(s));sb.auth.getSession().then(({data})=>hydrate(data.session));}else hydrateLocal();}
async function hydrate(session){state.user=session?.user||null;if(state.user){await ensureProfile();await loadCloud();showApp();}else showAuth();render();}
function hydrateLocal(){const local=JSON.parse(localStorage.getItem('libby_local_user')||'null');if(local){state.user={id:local.id,email:local.email};state.profile=local.profile;state.memories=JSON.parse(localStorage.getItem('libby_local_memories')||'[]');showApp();}else showAuth();render();}
async function ensureProfile(){const {data:p}=await sb.from('profiles').select('*').eq('id',state.user.id).maybeSingle();if(p){state.profile=p;return;}const name=state.user.user_metadata?.display_name||state.user.email?.split('@')[0]||'Libby User';const {data,error}=await sb.from('profiles').insert({id:state.user.id,email:state.user.email,display_name:name}).select('*').single();if(error)return toast(error.message);state.profile=data;}
async function loadCloud(){const [m,d]=await Promise.all([sb.from('memories').select('*').order('created_at',{ascending:false}).limit(100),sb.from('documents').select('*').order('created_at',{ascending:false}).limit(50)]);state.memories=m.data||[];state.documents=d.data||[];}
async function signUp(form){const name=form.display_name.value.trim(),email=form.email.value.trim(),password=form.password.value,referral=form.referral_code.value.trim();if(!name||!email||password.length<6)return toast('Name, email, and 6+ character password required.');if(!cloud){const user={id:'local_'+Date.now().toString(36),email,profile:{display_name:name,email,verification_status:'pending',referral_code:'LOCAL'}};localStorage.setItem('libby_local_user',JSON.stringify(user));hydrateLocal();return toast('Local app account created. Add app-config.js for cloud sync.');}const {data,error}=await sb.auth.signUp({email,password,options:{data:{display_name:name,referral_code:referral||null,preferred_contact_method:'written/email'}}});if(error)return toast(error.message);if(data.session)await hydrate(data.session);if(referral&&data.session)await sb.rpc('claim_referral',{code_input:referral});toast(data.session?'Account created.':'Check email to confirm account, then sign in.');}
async function signIn(form){if(!cloud)return toast('Cloud login needs app-config.js.');const {data,error}=await sb.auth.signInWithPassword({email:form.email.value.trim(),password:form.password.value});if(error)return toast(error.message);await hydrate(data.session);}
async function signOut(){if(sb)await sb.auth.signOut();localStorage.removeItem('libby_local_user');state.user=null;state.profile=null;state.memories=[];showAuth();render();}
async function saveMemory(text,title='Conversation note'){const body=text.trim();if(!body)return;if(cloud&&state.user){const {data,error}=await sb.from('memories').insert({owner_user_id:state.user.id,created_by:state.user.id,title,body,memory_type:'chat',confidence:'user_provided'}).select('*').single();if(error)return toast(error.message);state.memories.unshift(data);}else{const item={id:crypto.randomUUID(),title,body,created_at:new Date().toISOString(),confidence:'local_demo'};state.memories.unshift(item);localStorage.setItem('libby_local_memories',JSON.stringify(state.memories));}renderMemories();}
async function uploadFiles(files){if(!files?.length)return;if(!cloud||!state.user)return toast('File sync needs Supabase config and login.');for(const file of files){const path=`${state.user.id}/${Date.now()}-${file.name}`;const up=await sb.storage.from('libby-files').upload(path,file,{upsert:false});if(up.error){toast(up.error.message);continue;}await sb.from('documents').insert({owner_user_id:state.user.id,filename:file.name,storage_path:path,mime_type:file.type,size_bytes:file.size});}await loadCloud();render();toast('Files uploaded to private Libby storage.');}
async function createReferral(){if(!state.user)return toast('Sign in first.');if(!cloud)return toast('Referral codes need cloud mode.');const {data,error}=await sb.rpc('create_referral',{circle_id_input:null,role_input:'member'});if(error)return toast(error.message);toast(`Referral created: ${data.code}`);}
function fallbackReply(input){const q=input.toLowerCase();if(q.includes('api')||q.includes('key'))return 'I can use the model router once your backend is live. For now, I am still capturing notes locally so nothing breaks.';if(q.includes('hey libby'))return 'I am here. I can draft, remember, organize files, or prepare a human-facing summary. What should I handle first?';if(q.includes('referral'))return 'Create a referral code to connect overlapping users without exposing private memory by default.';if(q.includes('file'))return 'Use Files to upload. In cloud mode files are stored privately under your user ID.';return 'Captured. I saved that as a memory note and can turn it into a task, letter, brief, or dashboard item.';}
async function reply(input){try{const res=await fetch(modelApi,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[{role:'system',content:'You are Libby, a practical life assistant. Be direct, grounded, and useful. Help the user produce polished outputs, organize evidence, and take the next safe step.'},{role:'user',content:input}]})});if(!res.ok)throw new Error('router unavailable');const data=await res.json();return data.choices?.[0]?.message?.content||data.reply||fallbackReply(input);}catch(e){return fallbackReply(input);}}
async function sendAssistant(text){const clean=text.trim();if(!clean)return;addMsg(clean,'user');saveMemory(clean,'Chat capture');addMsg('Thinking…','libby');const answer=await reply(clean);const bubbles=document.querySelectorAll('.bubble.libby');const last=bubbles[bubbles.length-1];if(last&&last.textContent==='Thinking…')last.textContent=answer;else addMsg(answer,'libby');}
function addMsg(text,role='libby'){const log=$('assistantLog');if(!log)return;const div=document.createElement('div');div.className=`bubble ${role}`;div.textContent=text;log.appendChild(div);log.scrollTop=log.scrollHeight;}
function openAssistant(){state.assistantOpen=true;localStorage.setItem('libby_assistant_open','true');renderAssistant();setTimeout(()=>$('assistantInput')?.focus(),20)}function closeAssistant(){state.assistantOpen=false;localStorage.setItem('libby_assistant_open','false');renderAssistant()}function renderAssistant(){document.body.classList.toggle('assistant-open',state.assistantOpen)}function showAuth(){$('authView')?.classList.remove('hidden');$('appView')?.classList.add('hidden')}function showApp(){$('authView')?.classList.add('hidden');$('appView')?.classList.remove('hidden')}
function wire(){$('signupForm')?.addEventListener('submit',e=>{e.preventDefault();signUp(e.currentTarget)});$('signinForm')?.addEventListener('submit',e=>{e.preventDefault();signIn(e.currentTarget)});$('signOutBtn')?.addEventListener('click',signOut);$('assistantFab')?.addEventListener('click',openAssistant);$('assistantClose')?.addEventListener('click',closeAssistant);$('assistantSend')?.addEventListener('click',()=>{sendAssistant($('assistantInput').value);$('assistantInput').value=''});$('assistantInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('assistantSend').click()}});$('fileInput')?.addEventListener('change',e=>uploadFiles(e.target.files));$('referralBtn')?.addEventListener('click',createReferral);document.querySelectorAll('[data-tab]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b===btn));document.querySelectorAll('[data-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.panel!==btn.dataset.tab));}));}
function render(){renderAssistant();$('cloudStatus')&&($('cloudStatus').textContent=cloud?'Cloud sync ready':'Local preview: add app-config.js for Supabase sync');$('userName')&&($('userName').textContent=state.profile?.display_name||state.user?.email||'Guest');$('userEmail')&&($('userEmail').textContent=state.user?.email||'Not signed in');$('referralCode')&&($('referralCode').textContent=state.profile?.referral_code||'—');$('verificationStatus')&&($('verificationStatus').textContent=state.profile?.verification_status||'pending');renderMemories();renderFiles();}
function renderMemories(){const el=$('memoryList');if(!el)return;el.innerHTML=state.memories.length?state.memories.map(m=>`<article class="item"><b>${esc(m.title||'Memory')}</b><p>${esc(m.body)}</p><span>${esc(m.confidence||'user_provided')} · ${esc((m.created_at||'').slice(0,10))}</span></article>`).join(''):'<p class="muted">No memories yet. Talk to Libby or add files.</p>';}
function renderFiles(){const el=$('fileList');if(!el)return;el.innerHTML=state.documents.length?state.documents.map(d=>`<article class="item"><b>${esc(d.filename)}</b><span>${esc(d.mime_type||'file')} · ${Math.round((d.size_bytes||0)/1024)} KB</span></article>`).join(''):'<p class="muted">No cloud files uploaded yet.</p>';}
function toast(msg){const el=$('toast');if(!el)return alert(msg);el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),4200)}return{boot,openAssistant,closeAssistant}})();document.addEventListener('DOMContentLoaded',Libby.boot);
